# Generated by Django 3.2.10 on 2022-01-29 01:17

from django.db import migrations
from django.core.management import call_command


def forwards_func(apps, schema_editor):
    call_command("seed_data")


class Migration(migrations.Migration):

    dependencies = [
        ("opps", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            forwards_func, reverse_code=migrations.RunPython.noop, elidable=True
        ),
    ]
